#############################################################
# CFITSIO detection: pkg-config > environment > defaults
#
ifeq ($(shell pkg-config --exists cfitsio && echo yes),yes)
  CFITSIO_CFLAGS = $(shell pkg-config --cflags cfitsio)
  CFITSIO_LIBS   = $(shell pkg-config --libs cfitsio)
else
  CFITSIOINCDIR ?= /usr/local/include
  CFITSIO_CFLAGS = -I$(CFITSIOINCDIR)
  CFITSIO_LIBS   = -lcfitsio
endif

#
#
#############################################################
# INSTALL PATHS
#
PREFIX  ?= /usr/local
DESTDIR ?=

#
#
#############################################################
# COMPILATION OPTIONS
#

COPTS = -funroll-loops -O3 -ansi -Wall -Wno-unused-but-set-variable $(CFITSIO_CFLAGS) -I/usr/include/malloc
LIBS  = $(CFITSIO_LIBS) -lm

CC    = gcc

#
#
#############################################################
# BUILD TARGETS
#

STDH  = functions.h globals.h defaults.h
ALL   = main.o vargs.o alard.o functions.o

all:	hotpants

hotpants: $(ALL)
	$(CC) $(ALL) -o hotpants $(LIBS) $(COPTS)

main.o: $(STDH) main.c
	$(CC) $(COPTS) -c main.c

alard.o: $(STDH) alard.c
	$(CC) $(COPTS) -c alard.c

functions.o: $(STDH) functions.c
	$(CC) $(COPTS) -c functions.c

vargs.o: $(STDH) vargs.c
	$(CC) $(COPTS) -c vargs.c

NCOPTS = -funroll-loops -O3 $(CFITSIO_CFLAGS) -I/usr/include/malloc

extractkern: extractkern.c
	$(CC) $(NCOPTS) extractkern.c -o extractkern $(LIBS)

maskim: maskim.c
	$(CC) $(NCOPTS) maskim.c -o maskim $(LIBS)

install:
	install -d $(DESTDIR)$(PREFIX)/bin
	install -m 0755 hotpants $(DESTDIR)$(PREFIX)/bin/hotpants
	install -m 0755 maskim $(DESTDIR)$(PREFIX)/bin/maskim
	install -m 0755 extractkern $(DESTDIR)$(PREFIX)/bin/extractkern

clean:
	rm -f *.o
	rm -f *~ .*~
	rm -f hotpants
	rm -f extractkern
	rm -f maskim

.PHONY: all install clean
